<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Praxy.Core\Praxy.Core.csproj" />
    <ProjectReference Include="..\Praxy.Events\Praxy.Events.csproj" />
    <ProjectReference Include="..\Praxy.Persistence\Praxy.Persistence.csproj" />
  </ItemGroup>

</Project>
