// GENERATED by @praxy/codegen — do not edit by hand.
// Regenerate with:
//   npx praxy-codegen --endpoint http://localhost:5090 --project <project-id> --api-key <key> \
//     --database main --table todos --output <this-file>

import { Col } from "@praxy/core";

export interface Todo {
  title: string;
  done?: boolean;
}

export const TodoColumns = {
  id: new Col<string>("$id"),
  tableId: new Col<string>("$tableId"),
  databaseId: new Col<string>("$databaseId"),
  createdAt: new Col<string>("$createdAt"),
  updatedAt: new Col<string>("$updatedAt"),
  title: new Col<string>("title"),
  done: new Col<boolean>("done"),
};
