/**
 * Typed row interfaces + column-key `Col<T>` constants from a project's live schema — mirrors
 * `praxy_codegen`'s scope, widened slightly (row interfaces too, not just column constants — an
 * intentional widening for this SDK, not an inconsistency with the Dart CLI's narrower scope).
 * Deliberately not a bundler plugin or a watcher: generated files that show up in diffs beat a
 * codegen step that runs silently on every save.
 *
 * Talks to the data-plane schema API (`/v1/databases`) directly via `fetch` — API-key callers
 * only, the same boundary `DatabaseEndpoints.cs` draws (schema management is a server/CI concern).
 */

export interface CodegenOptions {
  endpoint: string;
  projectId: string;
  apiKey: string;
  /** The database's `key`, not its wire id. */
  database: string;
  /** The table's `key`, not its wire id. */
  table: string;
  /** Defaults to a PascalCase form of the table key. */
  className?: string;
}

interface SchemaColumn {
  key: string;
  type: string;
  array: boolean;
  required: boolean;
}

export class CodegenError extends Error {
  constructor(
    readonly path: string,
    readonly status: number,
    readonly body: string,
  ) {
    super(`${path} responded ${status}: ${body}`);
    this.name = "CodegenError";
  }
}

export async function generate(options: CodegenOptions, fetchImpl: typeof fetch = fetch): Promise<string> {
  const databases = await getJson<{ databases: Array<{ id: string; key: string }> }>(fetchImpl, options, "/v1/databases");
  const database = findByKey(databases.databases, options.database, "database");

  const tables = await getJson<{ tables: Array<{ id: string; key: string }> }>(
    fetchImpl,
    options,
    `/v1/databases/${database.id}/tables`,
  );
  const table = findByKey(tables.tables, options.table, "table");

  const { columns } = await getJson<{ columns: SchemaColumn[] }>(
    fetchImpl,
    options,
    `/v1/databases/${database.id}/tables/${table.id}/columns`,
  );

  return render(options.className ?? pascalCase(options.table), columns, {
    endpoint: options.endpoint,
    database: options.database,
    table: options.table,
  });
}

async function getJson<T>(fetchImpl: typeof fetch, options: CodegenOptions, path: string): Promise<T> {
  const response = await fetchImpl(`${options.endpoint.replace(/\/+$/, "")}${path}`, {
    headers: { "X-Praxy-Project": options.projectId, "X-Praxy-Key": options.apiKey, accept: "application/json" },
  });
  const body = await response.text();
  if (!response.ok) throw new CodegenError(path, response.status, body);
  try {
    return JSON.parse(body) as T;
  } catch {
    throw new CodegenError(path, response.status, body);
  }
}

function findByKey<T extends { key: string }>(items: T[], key: string, kind: string): T {
  const found = items.find((item) => item.key === key);
  if (!found) throw new Error(`No ${kind} with key '${key}' was found.`);
  return found;
}

const TYPE_MAP: Record<string, string> = {
  string: "string",
  email: "string",
  url: "string",
  ip: "string",
  enum: "string",
  integer: "number",
  float: "number",
  boolean: "boolean",
  datetime: "string",
};

function tsType(column: SchemaColumn): string {
  const scalar = TYPE_MAP[column.type] ?? "unknown";
  return column.array ? `${scalar}[]` : scalar;
}

function render(
  className: string,
  columns: SchemaColumn[],
  source: { endpoint: string; database: string; table: string },
): string {
  const fields = columns
    .map((c) => `  ${propertyKey(c.key)}${c.required ? "" : "?"}: ${tsType(c)};`)
    .join("\n");

  const systemConstants = [
    `  id: new Col<string>("$id"),`,
    `  tableId: new Col<string>("$tableId"),`,
    `  databaseId: new Col<string>("$databaseId"),`,
    `  createdAt: new Col<string>("$createdAt"),`,
    `  updatedAt: new Col<string>("$updatedAt"),`,
  ].join("\n");

  const columnConstants = columns
    .map((c) => `  ${propertyKey(c.key)}: new Col<${tsType(c)}>(${JSON.stringify(c.key)}),`)
    .join("\n");

  return `// GENERATED by @praxy/codegen — do not edit by hand.
// Regenerate with:
//   npx praxy-codegen --endpoint ${source.endpoint} --project <project-id> --api-key <key> \\
//     --database ${source.database} --table ${source.table} --output <this-file>

import { Col } from "@praxy/core";

export interface ${className} {
${fields}
}

export const ${className}Columns = {
${systemConstants}
${columnConstants}
};
`;
}

function propertyKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function pascalCase(key: string): string {
  const identifier = key
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  return /^[0-9]/.test(identifier) ? `T${identifier}` : identifier || "Row";
}
