#!/usr/bin/env sh
# Praxy launcher: installs Docker if it's missing, asks once whether this is a public
# deployment (and if so, for the domain), generates secrets + config accordingly, best-effort
# locks down the firewall for a public deployment, then hands off to docker compose.
set -eu
cd "$(dirname "$0")"

# ---- Docker ----------------------------------------------------------------------------------

install_docker_if_missing() {
  if command -v docker >/dev/null 2>&1; then
    return
  fi
  if [ "$(id -u)" != "0" ] || ! command -v apt-get >/dev/null 2>&1; then
    echo "Docker isn't installed, and this isn't a root apt-based (Ubuntu/Debian) system to" >&2
    echo "auto-install it on. Install Docker + the Compose plugin yourself:" >&2
    echo "  https://docs.docker.com/engine/install/" >&2
    exit 1
  fi

  echo "Docker not found — installing (Ubuntu, via apt)…"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  # shellcheck disable=SC1091
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  echo "Docker installed: $(docker --version)"
}

# ---- firewall (best-effort — never fails the run) --------------------------------------------

setup_firewall() {
  if ! command -v ufw >/dev/null 2>&1; then
    if [ "$(id -u)" = "0" ] && command -v apt-get >/dev/null 2>&1; then
      apt-get install -y -qq ufw 2>/dev/null || true
    fi
  fi
  if ! command -v ufw >/dev/null 2>&1; then
    echo "Note: ufw isn't available — skipping automatic firewall setup. Restrict this host's" >&2
    echo "inbound traffic to 22/80/443 yourself (a cloud security-group/firewall works too)." >&2
    return 0
  fi

  echo "Configuring ufw: allowing SSH/HTTP/HTTPS…"
  # Order matters: SSH must be allowed before enabling, or a remote session loses access the
  # moment new connections stop being implicitly allowed.
  ufw allow 22/tcp >/dev/null
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
  ufw --force enable >/dev/null
  echo "ufw enabled (22, 80, 443 open — everything else blocked at the host firewall)."
}

# ---- .env -------------------------------------------------------------------------------------

if [ ! -f .env ]; then
  echo "Generating deploy/.env with fresh secrets (first run)…"

  DOMAIN=""
  # Read the prompt from the controlling terminal, not stdin — works even when this script
  # itself arrived via `curl ... | sh`, where stdin is the script, not a human at a keyboard.
  # `[ -r /dev/tty ]` isn't a reliable enough check on its own — the device node can pass that
  # test even with no controlling terminal at all (e.g. a backgrounded/non-interactive run),
  # and failing mid-prompt with no fallback would abort the whole script under `set -e`. Actually
  # opening it on a spare fd is the only check that can't lie.
  if { exec 3<>/dev/tty; } 2>/dev/null; then
    printf "Public domain for this instance, e.g. praxy.example.com (leave blank to run over plain HTTP / localhost): " >&3
    read -r DOMAIN <&3 || DOMAIN=""
    exec 3>&-
  fi

  {
    echo "# Generated by up.sh — do not commit."
    echo "POSTGRES_PASSWORD=$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    echo "PRAXY_SECRET_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    echo "PRAXY_PORT=8080"
    if [ -n "$DOMAIN" ]; then
      echo "PRAXY_DOMAIN=$DOMAIN"
      echo "PRAXY_PUBLIC_URL=https://$DOMAIN"
      echo "PRAXY_TRUST_FORWARDED_HEADERS=true"
      echo "PRAXY_BIND=127.0.0.1"
      # Sites' wildcard subdomain, derived from the one domain already asked for above rather than
      # a second question (CLAUDE.md's "asks one question on first run" promise). Requires its own
      # wildcard DNS record (*.sites.$DOMAIN -> this host) — see docs/self-host.md.
      echo "PRAXY_SITES_DOMAIN=sites.$DOMAIN"
    else
      echo "# Set to your public origin (e.g. https://praxy.example.com) to require a"
      echo "# setup token — printed to the api container logs — when claiming."
      echo "PRAXY_PUBLIC_URL="
      echo "# Public deployment with automatic HTTPS: re-run with these three set (and"
      echo "# PRAXY_BIND=127.0.0.1), then 'docker compose --profile https up -d' instead of"
      echo "# this script — see docs/self-host.md."
      echo "PRAXY_DOMAIN="
      echo "PRAXY_TRUST_FORWARDED_HEADERS=false"
      echo "PRAXY_BIND=0.0.0.0"
      echo "PRAXY_SITES_DOMAIN=sites.localhost"
    fi
  } > .env
  chmod 600 .env
fi

install_docker_if_missing

# Read PRAXY_DOMAIN back out of .env — covers both the run that just generated it and every
# later run, so restarting the stack doesn't need to be told the profile again.
DOMAIN_SET=$(grep -E '^PRAXY_DOMAIN=' .env | cut -d= -f2- || true)

if [ -n "$DOMAIN_SET" ]; then
  setup_firewall || echo "Firewall setup failed — continuing anyway; lock it down manually." >&2
  exec docker compose --profile https up "$@"
else
  exec docker compose up "$@"
fi
