#!/usr/bin/env sh
# Praxy launcher: generates secrets into .env on first run, then hands off to docker compose.
set -eu
cd "$(dirname "$0")"

if [ ! -f .env ]; then
  echo "Generating deploy/.env with fresh secrets (first run)…"
  {
    echo "# Generated by up.sh — do not commit."
    echo "POSTGRES_PASSWORD=$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    echo "PRAXY_SECRET_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    echo "PRAXY_PORT=8080"
    echo "# Set to your public origin (e.g. https://praxy.example.com) to require a"
    echo "# setup token — printed to the api container logs — when claiming."
    echo "PRAXY_PUBLIC_URL="
    echo "# Public deployment with automatic HTTPS: set both, then run"
    echo "# 'docker compose --profile https up -d' instead of ./up.sh. See docs/self-host.md."
    echo "PRAXY_DOMAIN="
    echo "PRAXY_TRUST_FORWARDED_HEADERS=false"
  } > .env
  chmod 600 .env
fi

exec docker compose up "$@"
