using Microsoft.EntityFrameworkCore;
using Praxy.Core;
using Praxy.Functions;
using Praxy.Persistence;
using Praxy.Sites;

namespace Praxy.Api.Infrastructure;

/// <summary>
/// Bounds the disk a Praxy instance spends on Docker images it built itself.
///
/// <para>Every site and function deployment builds an image and <em>nothing ever removed one</em> —
/// found on the production droplet as every image ever built still present, the oldest two weeks
/// old, on a 77 GB disk that had already had to be hand-pruned once. A site wired to push-to-deploy
/// leaves roughly 300 MB behind per commit, forever, which is unbounded growth on the one resource
/// a self-hoster can't add more of without a migration.</para>
///
/// <para><b>Why bounded retention and not a prune.</b> An old deployment image is not garbage: it is
/// exactly what the console's "Activate" action rolls back to. Deleting every image but the running
/// one would silently turn rollback — the feature that makes a bad deploy survivable — into a
/// permanent one-way door. So this keeps a window
/// (<see cref="SitesOptions.KeepDeploymentImages"/> / <see cref="FunctionsOptions.KeepDeploymentImages"/>)
/// of the most recent successful builds per resource, plus the active deployment whatever its
/// age, and reclaims only what falls out the back.</para>
///
/// <para><b>Why the deployment id is read out of the image tag.</b> The tag is
/// <c>praxy-site-{deploymentId}:latest</c>, generated by this product and by nothing else, so the
/// tag alone says which deployment an image belongs to. That is what makes the orphan rule safe
/// without an age guard, which is the subtle part: a deployment row exists from the moment it is
/// <c>queued</c>, well before its build starts, so an image whose id matches <em>no row at all</em>
/// cannot be a build in flight — it can only be one whose deployment (or whose whole site, since
/// <c>SitesService.DeleteAsync</c> removes the row and never touched the image) is gone. Contrast
/// <c>SitePreviewSweeper</c>'s container reclaim, which does need an age guard: a container id is
/// written to the row <em>after</em> the container exists, so there "no row references it" genuinely
/// can mean "not yet."</para>
///
/// <para><b>Known residual:</b> a process killed between a successful build and the row update that
/// records its <c>ImageTag</c> leaves an image attached to a row stuck in <c>building</c> — matched
/// by neither rule, since the row exists but never reaches <c>ready</c>. Bounded by how often the
/// process dies mid-build rather than by deploy volume, so it is not the unbounded growth this
/// replaces; reclaiming it would need the age guard the two rules above are specifically shaped to
/// avoid needing.</para>
/// </summary>
public sealed class DeploymentImageSweeper(
    IServiceScopeFactory scopeFactory,
    SiteDockerExecutor siteDocker,
    DockerExecutor functionDocker,
    SitesOptions sitesOptions,
    FunctionsOptions functionsOptions,
    RetentionOptions retentionOptions,
    ILogger<DeploymentImageSweeper> logger) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            await SweepAsync(stoppingToken);

            try
            {
                await Task.Delay(TimeSpan.FromSeconds(retentionOptions.SweepIntervalSeconds), stoppingToken);
            }
            catch (OperationCanceledException)
            {
                break;
            }
        }
    }

    private async Task SweepAsync(CancellationToken ct)
    {
        using var scope = scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<PraxyDb>();

        // Guarded separately rather than under one try. Sites and Functions can be pointed at
        // different daemons (Praxy:Sites:DockerEndpoint / Praxy:Functions:DockerEndpoint), so one
        // unreachable endpoint must not silently stop the other subsystem being reclaimed — that
        // failure mode looks exactly like "there was nothing to reclaim" and would go unnoticed
        // until a disk filled up, which is the whole failure this service exists to prevent.
        var siteReclaimed = await TryAsync("site", () => SweepSitesAsync(db, ct));
        var functionReclaimed = await TryAsync("function", () => SweepFunctionsAsync(db, ct));

        if (siteReclaimed + functionReclaimed > 0)
            logger.LogInformation(
                "Reclaimed {SiteCount} site and {FunctionCount} function deployment image(s)",
                siteReclaimed, functionReclaimed);
    }

    /// <summary>Runs one subsystem's sweep, logging and swallowing its failure so the other still runs.</summary>
    private async Task<int> TryAsync(string subsystem, Func<Task<int>> sweep)
    {
        try
        {
            return await sweep();
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            logger.LogError(ex, "Deployment image sweep failed for {Subsystem}", subsystem);
            return 0;
        }
    }

    private async Task<int> SweepSitesAsync(PraxyDb db, CancellationToken ct)
    {
        var tags = await siteDocker.ListDeploymentImageTagsAsync(ct);
        if (tags.Count == 0)
            return 0;

        // Only the columns the policy needs. A deployment row carries its whole build log, and this
        // reads every deployment in the instance.
        var deployments = await db.SiteDeployments
            .Select(d => new DeploymentRow(d.Id, d.SiteId, d.Status, d.CreatedAt))
            .ToListAsync(ct);
        var active = await db.Sites
            .Where(s => s.ActiveDeploymentId != null)
            .Select(s => s.ActiveDeploymentId!.Value)
            .ToListAsync(ct);

        var expendable = Expendable(tags, SiteDockerExecutor.ImageTagPrefix, deployments, active,
            sitesOptions.KeepDeploymentImages);

        var reclaimed = 0;
        foreach (var (tag, deploymentId) in expendable)
        {
            if (!await siteDocker.RemoveImageAsync(tag, ct))
                continue;
            reclaimed++;

            // Only after the image is actually gone. ImageTag is documented as "the built Docker
            // image tag" — a row still naming an image that no longer exists is a lie the console
            // renders and ActivateAsync trusts, so the column and the daemon must agree. Clearing
            // it is also what stops the console offering a rollback that could only fail.
            await db.SiteDeployments
                .Where(d => d.Id == deploymentId)
                .ExecuteUpdateAsync(s => s.SetProperty(d => d.ImageTag, (string?)null), ct);
        }
        return reclaimed;
    }

    private async Task<int> SweepFunctionsAsync(PraxyDb db, CancellationToken ct)
    {
        var tags = await functionDocker.ListDeploymentImageTagsAsync(ct);
        if (tags.Count == 0)
            return 0;

        var deployments = await db.FunctionDeployments
            .Select(d => new DeploymentRow(d.Id, d.FunctionId, d.Status, d.CreatedAt))
            .ToListAsync(ct);
        var active = await db.Functions
            .Where(f => f.ActiveDeploymentId != null)
            .Select(f => f.ActiveDeploymentId!.Value)
            .ToListAsync(ct);

        var expendable = Expendable(tags, DockerExecutor.ImageTagPrefix, deployments, active,
            functionsOptions.KeepDeploymentImages);

        var reclaimed = 0;
        foreach (var (tag, deploymentId) in expendable)
        {
            if (!await functionDocker.RemoveImageAsync(tag, ct))
                continue;
            reclaimed++;
            await db.FunctionDeployments
                .Where(d => d.Id == deploymentId)
                .ExecuteUpdateAsync(s => s.SetProperty(d => d.ImageTag, (string?)null), ct);
        }
        return reclaimed;
    }

    /// <summary>A deployment reduced to what the retention policy needs, for sites and functions alike.</summary>
    public readonly record struct DeploymentRow(Guid Id, Guid ParentId, string Status, DateTimeOffset CreatedAt);

    /// <summary>
    /// The two rules, applied to one subsystem's images. Pure and static so
    /// <c>DeploymentImageRetentionTests</c> can exercise the policy directly rather than only
    /// through a live Docker daemon — the rules are where a mistake silently deletes a rollback
    /// target, and that deserves cheaper tests than a container.
    ///
    /// <para>Rule 1 — <b>orphan</b>: no deployment row has this id, so the deployment or its whole
    /// site/function is gone.</para>
    /// <para>Rule 2 — <b>past the window</b>: the row is <c>ready</c>, is not its resource's active
    /// deployment, and is not among the <paramref name="keep"/> most recently created <c>ready</c>
    /// deployments of that resource.</para>
    /// <para>Anything else — a row that exists but has not reached <c>ready</c> — is left alone; see
    /// the class summary's residual note.</para>
    /// </summary>
    public static List<(string Tag, Guid DeploymentId)> Expendable(
        IReadOnlyList<string> tags,
        string tagPrefix,
        IReadOnlyList<DeploymentRow> deployments,
        IReadOnlyList<Guid> activeDeploymentIds,
        int keep)
    {
        var byId = deployments.ToDictionary(d => d.Id);
        var active = activeDeploymentIds.ToHashSet();

        // The keep-window is per resource, not per instance: one busy site must never push another
        // site's only rollback target off the end of a global list.
        var withinWindow = deployments
            .Where(d => d.Status == "ready")
            .GroupBy(d => d.ParentId)
            .SelectMany(g => g.OrderByDescending(d => d.CreatedAt).Take(Math.Max(keep, 0)))
            .Select(d => d.Id)
            .ToHashSet();

        var expendable = new List<(string, Guid)>();
        foreach (var tag in tags)
        {
            if (!TryParseDeploymentId(tag, tagPrefix, out var deploymentId))
                continue;

            if (!byId.TryGetValue(deploymentId, out var deployment))
            {
                expendable.Add((tag, deploymentId)); // Rule 1.
                continue;
            }

            if (deployment.Status == "ready"
                && !active.Contains(deploymentId)
                && !withinWindow.Contains(deploymentId))
            {
                expendable.Add((tag, deploymentId)); // Rule 2.
            }
        }
        return expendable;
    }

    /// <summary>
    /// <c>praxy-site-0199…:latest</c> → the deployment's <see cref="Guid"/>. A tag that doesn't parse
    /// is skipped rather than treated as an orphan: this filter is the only thing standing between
    /// the policy and an unrelated image that happens to share the prefix, so it fails closed.
    /// </summary>
    private static bool TryParseDeploymentId(string tag, string tagPrefix, out Guid deploymentId)
    {
        deploymentId = default;
        if (!tag.StartsWith(tagPrefix, StringComparison.Ordinal))
            return false;

        var rest = tag.AsSpan(tagPrefix.Length);
        var colon = rest.IndexOf(':');
        if (colon >= 0)
            rest = rest[..colon];
        return Ids.TryParseWire(rest.ToString(), out deploymentId);
    }
}
