import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

final class CodegenOptions {
  const CodegenOptions({
    required this.endpoint,
    required this.projectId,
    required this.apiKey,
    required this.databaseKey,
    required this.tableKey,
    required this.outputPath,
    this.className,
  });

  final String endpoint;
  final String projectId;
  final String apiKey;
  final String databaseKey;
  final String tableKey;
  final String outputPath;
  final String? className;
}

final class CodegenException implements Exception {
  CodegenException(this.message);
  final String message;
  @override
  String toString() => message;
}

/// Fetches a table's columns from a running Praxy instance and writes a small,
/// committed Dart file of typed `Col<T>` constants. Run by hand whenever the
/// schema changes — not a `build_runner` builder, so it never runs on save and its
/// output shows up in diffs like any other source file.
Future<void> generate(CodegenOptions options, {http.Client? client}) async {
  final httpClient = client ?? http.Client();
  try {
    final headers = {'x-praxy-project': options.projectId, 'x-praxy-key': options.apiKey};
    final base = Uri.parse(options.endpoint);

    final database = await _findByKey(httpClient, base, headers, '/v1/databases', 'databases', options.databaseKey);
    final databaseId = database['id'] as String;

    final table = await _findByKey(
      httpClient,
      base,
      headers,
      '/v1/databases/$databaseId/tables',
      'tables',
      options.tableKey,
    );
    final tableId = table['id'] as String;

    final columnsJson = await _getJson(
      httpClient,
      base,
      headers,
      '/v1/databases/$databaseId/tables/$tableId/columns',
    );
    final columns = (columnsJson['columns'] as List).cast<Map<String, dynamic>>();

    final code = _render(
      className: options.className ?? '${_pascalCase(options.tableKey)}Columns',
      databaseKey: options.databaseKey,
      tableKey: options.tableKey,
      columns: columns,
    );

    final file = File(options.outputPath);
    await file.parent.create(recursive: true);
    await file.writeAsString(code);
  } finally {
    if (client == null) httpClient.close();
  }
}

Future<Map<String, dynamic>> _findByKey(
  http.Client client,
  Uri base,
  Map<String, String> headers,
  String path,
  String listField,
  String key,
) async {
  final json = await _getJson(client, base, headers, path);
  final items = (json[listField] as List).cast<Map<String, dynamic>>();
  for (final item in items) {
    if (item['key'] == key) return item;
  }
  throw CodegenException("No '$listField' entry with key '$key' found at $path.");
}

Future<Map<String, dynamic>> _getJson(
  http.Client client,
  Uri base,
  Map<String, String> headers,
  String path,
) async {
  final response = await client.get(base.resolve(path), headers: headers);
  if (response.statusCode >= 400) {
    throw CodegenException('GET $path failed: HTTP ${response.statusCode} ${response.body}');
  }
  return jsonDecode(response.body) as Map<String, dynamic>;
}

String _render({
  required String className,
  required String databaseKey,
  required String tableKey,
  required List<Map<String, dynamic>> columns,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY praxy_codegen — do not hand-edit.')
    ..writeln('// Table: $tableKey (database: $databaseKey)')
    ..writeln('// Regenerate: dart run praxy_codegen --database $databaseKey --table $tableKey ...')
    ..writeln()
    ..writeln("import 'package:praxy_core/praxy_core.dart';")
    ..writeln()
    ..writeln('abstract final class $className {')
    ..writeln("  static const id = Col<String>(r'\$id');")
    ..writeln("  static const createdAt = Col<DateTime>(r'\$createdAt');")
    ..writeln("  static const updatedAt = Col<DateTime>(r'\$updatedAt');");

  for (final column in columns) {
    final key = column['key'] as String;
    final type = column['type'] as String;
    final isArray = column['array'] as bool? ?? false;
    final fieldName = _camelCase(key);
    final dartType = _dartType(type, isArray);
    buffer.writeln("  static const $fieldName = Col<$dartType>('$key');");
  }

  buffer.writeln('}');
  return buffer.toString();
}

String _dartType(String columnType, bool isArray) {
  final scalar = switch (columnType) {
    'string' || 'email' || 'url' || 'ip' || 'enum' => 'String',
    'integer' => 'int',
    'float' => 'double',
    'boolean' => 'bool',
    'datetime' => 'DateTime',
    _ => 'Object?',
  };
  return isArray ? 'List<$scalar>' : scalar;
}

const _dartKeywords = {
  'abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch', 'class', 'const',
  'continue', 'covariant', 'default', 'deferred', 'do', 'dynamic', 'else', 'enum', 'export',
  'extends', 'extension', 'external', 'factory', 'false', 'final', 'finally', 'for', 'Function',
  'get', 'hide', 'if', 'implements', 'import', 'in', 'interface', 'is', 'library', 'mixin', 'new',
  'null', 'on', 'operator', 'part', 'required', 'rethrow', 'return', 'set', 'show', 'static',
  'super', 'switch', 'sync', 'this', 'throw', 'true', 'try', 'typedef', 'var', 'void', 'while',
  'with', 'yield',
};

String _camelCase(String key) {
  final parts = key.split(RegExp(r'[_\-\s]+')).where((p) => p.isNotEmpty).toList();
  if (parts.isEmpty) return '_';
  final first = parts.first.toLowerCase();
  final rest = parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1).toLowerCase());
  final name = [first, ...rest].join();
  return _dartKeywords.contains(name) ? '${name}_' : name;
}

String _pascalCase(String key) {
  final camel = _camelCase(key);
  return camel[0].toUpperCase() + camel.substring(1);
}
