<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Praxy.Core\Praxy.Core.csproj" />
    <ProjectReference Include="..\Praxy.Persistence\Praxy.Persistence.csproj" />
  </ItemGroup>

</Project>
